angular.ngAppName = "kacoo.test";

angular.module(angular.ngAppName, [])

    .controller('indexController', ['$scope', '$templateRequest',
        function ($scope, $templateRequest) {
            $scope.click = function (flag) {
                alert(flag);
            }

            // $templateRequest('./test_data/appointment.json')
            // .then(function(appointmentInfo) {
            //     var list  = appointmentInfo;
            //     console.log(list);

            //     }, function(reason) {
            //         console.log(reason);
            //     })

            var appointmentInfo = {
                "success": true,
                "content": {
                    "content": [
                        {
                            "fileNumber": null,
                            "transactorMaskIdNo": null,
                            "transactorIdType": null,
                            "bizTypeName": "档案查询",
                            "source": "快速预约",
                            "idNo": "t",
                            "transactorIdName": null,
                            "proxyIdName": null,
                            "proxyIdNo": null,
                            "idName": null,
                            "appointmentStartTime": "2019-04-16 15:30:00",
                            "state": "booked",
                            "id": 2566,
                            "isDelay": 0,
                            "engineNo": null,
                            "amount": null,
                            "plateNo": null,
                            "plateType": null,
                            "mobile": null,
                            "appointmentEndTime": "2019-04-16 17:00:00",
                            "appointmentNo": "20190416VEH0501168",
                            "expiredTime": null,
                            "bizStationName": "芳村分所",
                            "vehicleNo": null,
                            "checkTime": null,
                            "createTime": "2019-04-16 15:13:20",
                            "cancelTime": null,
                            "transactorIdNo": null,
                            "appointmentDate": "2019-04-16"
                        },
                        {
                            "fileNumber": null,
                            "transactorMaskIdNo": null,
                            "transactorIdType": null,
                            "bizTypeName": "档案查询",
                            "source": "快速预约",
                            "idNo": "t",
                            "transactorIdName": null,
                            "proxyIdName": null,
                            "proxyIdNo": null,
                            "idName": null,
                            "appointmentStartTime": "2019-04-16 15:30:00",
                            "state": "booked",
                            "id": 2564,
                            "isDelay": 0,
                            "engineNo": null,
                            "amount": null,
                            "plateNo": null,
                            "plateType": null,
                            "mobile": null,
                            "appointmentEndTime": "2019-04-16 17:00:00",
                            "appointmentNo": "20190416VEH0501166",
                            "expiredTime": null,
                            "bizStationName": "芳村分所",
                            "vehicleNo": null,
                            "checkTime": null,
                            "createTime": "2019-04-16 15:05:12",
                            "cancelTime": null,
                            "transactorIdNo": null,
                            "appointmentDate": "2019-04-16"
                        },
                        {
                            "fileNumber": null,
                            "transactorMaskIdNo": null,
                            "transactorIdType": null,
                            "bizTypeName": "档案查询",
                            "source": "快速预约",
                            "idNo": "t",
                            "transactorIdName": null,
                            "proxyIdName": null,
                            "proxyIdNo": null,
                            "idName": null,
                            "appointmentStartTime": "2019-04-16 15:30:00",
                            "state": "booked",
                            "id": 2563,
                            "isDelay": 0,
                            "engineNo": null,
                            "amount": null,
                            "plateNo": null,
                            "plateType": null,
                            "mobile": null,
                            "appointmentEndTime": "2019-04-16 17:00:00",
                            "appointmentNo": "20190416VEH0501165",
                            "expiredTime": null,
                            "bizStationName": "芳村分所",
                            "vehicleNo": null,
                            "checkTime": null,
                            "createTime": "2019-04-16 15:04:35",
                            "cancelTime": null,
                            "transactorIdNo": null,
                            "appointmentDate": "2019-04-16"
                        },
                        {
                            "fileNumber": null,
                            "transactorMaskIdNo": null,
                            "transactorIdType": null,
                            "bizTypeName": "档案查询",
                            "source": "快速预约",
                            "idNo": "t",
                            "transactorIdName": null,
                            "proxyIdName": null,
                            "proxyIdNo": null,
                            "idName": null,
                            "appointmentStartTime": "2019-04-16 15:30:00",
                            "state": "booked",
                            "id": 2562,
                            "isDelay": 0,
                            "engineNo": null,
                            "amount": null,
                            "plateNo": null,
                            "plateType": null,
                            "mobile": null,
                            "appointmentEndTime": "2019-04-16 17:00:00",
                            "appointmentNo": "20190416VEH0501164",
                            "expiredTime": null,
                            "bizStationName": "芳村分所",
                            "vehicleNo": null,
                            "checkTime": null,
                            "createTime": "2019-04-16 15:01:48",
                            "cancelTime": null,
                            "transactorIdNo": null,
                            "appointmentDate": "2019-04-16"
                        },
                        {
                            "fileNumber": null,
                            "transactorMaskIdNo": null,
                            "transactorIdType": null,
                            "bizTypeName": "档案查询",
                            "source": "快速预约",
                            "idNo": "t",
                            "transactorIdName": null,
                            "proxyIdName": null,
                            "proxyIdNo": null,
                            "idName": null,
                            "appointmentStartTime": "2019-04-16 15:30:00",
                            "state": "booked",
                            "id": 2561,
                            "isDelay": 0,
                            "engineNo": null,
                            "amount": null,
                            "plateNo": null,
                            "plateType": null,
                            "mobile": null,
                            "appointmentEndTime": "2019-04-16 17:00:00",
                            "appointmentNo": "20190416VEH0501163",
                            "expiredTime": null,
                            "bizStationName": "芳村分所",
                            "vehicleNo": null,
                            "checkTime": null,
                            "createTime": "2019-04-16 15:01:34",
                            "cancelTime": null,
                            "transactorIdNo": null,
                            "appointmentDate": "2019-04-16"
                        },
                        {
                            "fileNumber": null,
                            "transactorMaskIdNo": null,
                            "transactorIdType": null,
                            "bizTypeName": "注册/变更互联网服务平台（个人或单位）及变更网上车管所联系方式",
                            "source": "快速预约",
                            "idNo": "1",
                            "transactorIdName": null,
                            "proxyIdName": null,
                            "proxyIdNo": null,
                            "idName": null,
                            "appointmentStartTime": "2019-04-16 13:00:00",
                            "state": "booked",
                            "id": 2572,
                            "isDelay": 0,
                            "engineNo": null,
                            "amount": null,
                            "plateNo": null,
                            "plateType": null,
                            "mobile": null,
                            "appointmentEndTime": "2019-04-16 14:00:00",
                            "appointmentNo": "20190416DL2401174",
                            "expiredTime": null,
                            "bizStationName": "白云分所",
                            "vehicleNo": null,
                            "checkTime": null,
                            "createTime": "2019-04-16 12:33:48",
                            "cancelTime": null,
                            "transactorIdNo": null,
                            "appointmentDate": "2019-04-16"
                        },
                        {
                            "fileNumber": null,
                            "transactorMaskIdNo": null,
                            "transactorIdType": null,
                            "bizTypeName": "注册/变更互联网服务平台（个人或单位）及变更网上车管所联系方式",
                            "source": "快速预约",
                            "idNo": "1",
                            "transactorIdName": null,
                            "proxyIdName": null,
                            "proxyIdNo": null,
                            "idName": null,
                            "appointmentStartTime": "2019-04-16 13:00:00",
                            "state": "booked",
                            "id": 2571,
                            "isDelay": 0,
                            "engineNo": null,
                            "amount": null,
                            "plateNo": null,
                            "plateType": null,
                            "mobile": null,
                            "appointmentEndTime": "2019-04-16 14:00:00",
                            "appointmentNo": "20190416DL2401173",
                            "expiredTime": null,
                            "bizStationName": "白云分所",
                            "vehicleNo": null,
                            "checkTime": null,
                            "createTime": "2019-04-16 12:32:26",
                            "cancelTime": null,
                            "transactorIdNo": null,
                            "appointmentDate": "2019-04-16"
                        },
                        {
                            "fileNumber": null,
                            "transactorMaskIdNo": null,
                            "transactorIdType": null,
                            "bizTypeName": "注册/变更互联网服务平台（个人或单位）及变更网上车管所联系方式",
                            "source": "快速预约",
                            "idNo": "1",
                            "transactorIdName": null,
                            "proxyIdName": null,
                            "proxyIdNo": null,
                            "idName": null,
                            "appointmentStartTime": "2019-04-16 13:00:00",
                            "state": "booked",
                            "id": 2570,
                            "isDelay": 0,
                            "engineNo": null,
                            "amount": null,
                            "plateNo": null,
                            "plateType": null,
                            "mobile": null,
                            "appointmentEndTime": "2019-04-16 14:00:00",
                            "appointmentNo": "20190416DL2401172",
                            "expiredTime": null,
                            "bizStationName": "白云分所",
                            "vehicleNo": null,
                            "checkTime": null,
                            "createTime": "2019-04-16 12:32:24",
                            "cancelTime": null,
                            "transactorIdNo": null,
                            "appointmentDate": "2019-04-16"
                        },
                        {
                            "fileNumber": null,
                            "transactorMaskIdNo": null,
                            "transactorIdType": null,
                            "bizTypeName": "注册/变更互联网服务平台（个人或单位）及变更网上车管所联系方式",
                            "source": "快速预约",
                            "idNo": "1",
                            "transactorIdName": null,
                            "proxyIdName": null,
                            "proxyIdNo": null,
                            "idName": null,
                            "appointmentStartTime": "2019-04-16 13:00:00",
                            "state": "booked",
                            "id": 2569,
                            "isDelay": 0,
                            "engineNo": null,
                            "amount": null,
                            "plateNo": null,
                            "plateType": null,
                            "mobile": null,
                            "appointmentEndTime": "2019-04-16 14:00:00",
                            "appointmentNo": "20190416DL2401171",
                            "expiredTime": null,
                            "bizStationName": "白云分所",
                            "vehicleNo": null,
                            "checkTime": null,
                            "createTime": "2019-04-16 12:32:21",
                            "cancelTime": null,
                            "transactorIdNo": null,
                            "appointmentDate": "2019-04-16"
                        },
                        {
                            "fileNumber": null,
                            "transactorMaskIdNo": null,
                            "transactorIdType": null,
                            "bizTypeName": "档案查询",
                            "source": "快速预约",
                            "idNo": "1",
                            "transactorIdName": null,
                            "proxyIdName": null,
                            "proxyIdNo": null,
                            "idName": null,
                            "appointmentStartTime": "2019-04-16 15:30:00",
                            "state": "booked",
                            "id": 2568,
                            "isDelay": 0,
                            "engineNo": null,
                            "amount": null,
                            "plateNo": null,
                            "plateType": null,
                            "mobile": null,
                            "appointmentEndTime": "2019-04-16 17:00:00",
                            "appointmentNo": "20190416VEH0501170",
                            "expiredTime": null,
                            "bizStationName": "芳村分所",
                            "vehicleNo": null,
                            "checkTime": null,
                            "createTime": "2019-04-16 12:30:58",
                            "cancelTime": null,
                            "transactorIdNo": null,
                            "appointmentDate": "2019-04-16"
                        }
                    ],
                    "pageable": {
                        "sort": {
                            "sorted": false,
                            "unsorted": true
                        },
                        "offset": 0,
                        "pageSize": 10,
                        "pageNumber": 0,
                        "unpaged": false,
                        "paged": true
                    },
                    "totalPages": 54,
                    "last": false,
                    "totalElements": 536,
                    "number": 0,
                    "size": 10,
                    "sort": {
                        "sorted": false,
                        "unsorted": true
                    },
                    "first": true,
                    "numberOfElements": 10
                }
            };
            $scope.list = appointmentInfo.content.content;
            console.log($scope.list);
        }])